### ISSUE TITLE
running the library

### ISSUE THREAD

**Issue by aakzubaidi** [aled/jsi-examples#2]
Hi, I am very interested in using the library in my master degree project. However, I copied the examples such as "NearestN" to see how they work and be able to figure out how to use it. however I end up with this error.
note that please, I am not a maven user and not familiar with such a thing.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

import used are the following 
import org.slf4j._;
import com.infomatiq.jsi._;
import gnu.trove.*;

thank you

**Comment by aakzubaidi** [comment]
I hope if there is any tutorial you can refer me to, so I can deal with it properly

**Comment by aled** [comment]
Hi, the reason you are getting 'Failed to load class' errors is because the JSI library will only work if you have some other libraries installed first.

Maven is used to automatically download these dependencies for you; It is very easy to use, first install it from here: http://maven.apache.org/download.cgi and then follow the instructions at the bottom of the main jsi-examples page here: https://github.com/aled/jsi-examples

Feel free to raise another issue if the instructions do not work.
